@startuml
autonumber
participant program #white
participant update #white
participant view #white

program -> view : Отрисовывает представление
|||
view -> program : Отправляет сообщение, например, Expand
program -> update : Перенаправляет сообщение с текущим состоянием
update --> program : Возвращает обновлённое состояние и команду
program -> view : Отрисовывает представление
@enduml
